deployments:
  - name: artifacts
    entrypoint: artifact_flow.py:artifacts_flow
    work_pool:
      name: kubernetes-gke-worker-dev
      job_variables: {
        image: prefecthq/prefect-dev:main-python3.10
      }
        
  - name: sync_async
    entrypoint: async_sync_flow.py:sync_async_flow
    work_pool:
      name: kubernetes-gke-worker-dev
      job_variables: {
        image: prefecthq/prefect-dev:main-python3.10
      }
  
  - name: mapped_tasks
    entrypoint: mapped_tasks_flow.py:many_mapped_tasks_flow
    work_pool:
      name: kubernetes-gke-worker-dev
      job_variables: {
        image: prefecthq/prefect-dev:main-python3.10
      }

  - name: mapped_tasks_hanging
    entrypoint: mapped_tasks_hanging_flow.py:hanging_mapped_tasks_flow
    work_pool:
      name: kubernetes-gke-worker-dev
      job_variables: {
        image: prefecthq/prefect-dev:main-python3.10
      }